In [1]:
import numpy as np

In [54]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Zero
Ones
arange
random.rand
linspace
array
empty

In [5]:
Z=np.zeros(5)

In [6]:
Z

array([0., 0., 0., 0., 0.])

In [8]:
Z=np.ones(5)
Z

array([1., 1., 1., 1., 1.])

In [9]:
A=np.arange(0,10,2)
A

array([0, 2, 4, 6, 8])

In [10]:
arr=np.random.rand(5) #It always gives random numbers from 0 to 1
arr

array([0.22198109, 0.15852578, 0.37102378, 0.64587973, 0.78950139])

In [11]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
e=np.empty(7)
e

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.33511018e-306,
       1.89146896e-307, 7.56571288e-307, 5.18689447e+180])

**2D arrays**

In [15]:
arr2=np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
Z=np.zeros([5,5])
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
O=np.ones([5,5])
O

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
x=np.random.rand(5,5)
x

array([[0.89269776, 0.33472765, 0.74722302, 0.711665  , 0.60491037],
       [0.26140497, 0.76256585, 0.3371426 , 0.69484947, 0.81708264],
       [0.89542464, 0.06248076, 0.09664609, 0.49373117, 0.91242352],
       [0.2506801 , 0.87528658, 0.69399766, 0.48624786, 0.34377204],
       [0.84122833, 0.09532397, 0.93235746, 0.82070521, 0.07145925]])

In [29]:
x=np.random.rand(5,5,5)
x

array([[[0.84725782, 0.56759851, 0.22493168, 0.71768946, 0.08151456],
        [0.37067062, 0.40908759, 0.68946177, 0.57942343, 0.76121656],
        [0.49640169, 0.76497656, 0.44893943, 0.32948461, 0.86765361],
        [0.73541297, 0.81186366, 0.6748234 , 0.77650403, 0.0037183 ],
        [0.69162107, 0.13613084, 0.69488857, 0.67323002, 0.97597505]],

       [[0.72395391, 0.02949728, 0.3469247 , 0.80660834, 0.82863058],
        [0.74265017, 0.57333055, 0.93543833, 0.75829739, 0.53679001],
        [0.0929009 , 0.83272738, 0.7173916 , 0.42269857, 0.51621382],
        [0.38008511, 0.80053874, 0.81816985, 0.43415947, 0.17932782],
        [0.41473598, 0.90615824, 0.54059299, 0.6919891 , 0.12107045]],

       [[0.86130399, 0.34455084, 0.83298452, 0.45109901, 0.78917746],
        [0.73373382, 0.79715861, 0.95880977, 0.29537142, 0.43157602],
        [0.43743882, 0.48821886, 0.37206365, 0.79558913, 0.58806802],
        [0.55884965, 0.34451916, 0.07757183, 0.98014206, 0.95543109],
        [0.95949

In [31]:
arr

array([0.22198109, 0.15852578, 0.37102378, 0.64587973, 0.78950139])

In [32]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Size, shape, dtype

In [33]:
print(arr.size)

5


In [34]:
print(arr2.size)

9


In [35]:
print(arr.shape)

(5,)


In [36]:
print(arr2.shape)

(3, 3)


**Operations in Array**
copy
sort
reshape

In [38]:
arr3=np.copy(arr2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr3[2,2]=10
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [42]:
arr3[1,2]=12
arr3[2,1]=15
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 15, 10]])

In [43]:
arr3=np.sort(arr3)
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

In [44]:
arr3=np.sort(arr3, axis=0)
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

axis 0 --> downwards, vertical
axis 1 --> left to right, horizantal

In [46]:
arr

array([0.22198109, 0.15852578, 0.37102378, 0.64587973, 0.78950139])

In [47]:
np.append(arr, 10)

array([ 0.22198109,  0.15852578,  0.37102378,  0.64587973,  0.78950139,
       10.        ])

In [49]:
arr=np.append(arr,10)
arr

array([ 0.22198109,  0.15852578,  0.37102378,  0.64587973,  0.78950139,
       10.        , 10.        ])

In [50]:
arr=np.delete(arr,6,axis=0)
arr

array([ 0.22198109,  0.15852578,  0.37102378,  0.64587973,  0.78950139,
       10.        ])

In [53]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [55]:
arr=np.append(arr,10)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr=np.delete(arr,6,axis=0)
arr

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [57]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

In [60]:
arr4=np.concatenate((arr2, arr3), axis=0)
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

In [62]:
arr5=np.concatenate((arr2, arr3), axis=1)
arr5

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7, 10, 15]])

In [64]:
arr6=np.split(arr4, 3)
arr6

[array([[1, 2, 3, 1, 2, 3]]),
 array([[ 4,  5,  6,  4,  5, 12]]),
 array([[ 7,  8,  9,  7, 10, 15]])]

In [65]:
arr6[0]

array([[1, 2, 3, 1, 2, 3]])

In [67]:
arr6[1]

array([[ 4,  5,  6,  4,  5, 12]])

In [68]:
arr6[2]

array([[ 7,  8,  9,  7, 10, 15]])

**Scalar Expressions**
add
subtract
multiply
divide
power

In [69]:
arr5

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7, 10, 15]])

In [70]:
np.add(arr5,1)

array([[ 2,  3,  4,  2,  3,  4],
       [ 5,  6,  7,  5,  6, 13],
       [ 8,  9, 10,  8, 11, 16]])

In [72]:
np.subtract(arr5,1)

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4, 11],
       [ 6,  7,  8,  6,  9, 14]])

In [74]:
np.multiply(arr5,5)

array([[ 5, 10, 15,  5, 10, 15],
       [20, 25, 30, 20, 25, 60],
       [35, 40, 45, 35, 50, 75]])

In [75]:
np.divide(arr5,2)

array([[0.5, 1. , 1.5, 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 2. , 2.5, 6. ],
       [3.5, 4. , 4.5, 3.5, 5. , 7.5]])

In [76]:
np.power(arr5,3)

array([[   1,    8,   27,    1,    8,   27],
       [  64,  125,  216,   64,  125, 1728],
       [ 343,  512,  729,  343, 1000, 3375]], dtype=int32)

**Vector Expressions**

In [78]:
arr6

[array([[1, 2, 3, 1, 2, 3]]),
 array([[ 4,  5,  6,  4,  5, 12]]),
 array([[ 7,  8,  9,  7, 10, 15]])]

In [80]:
arr7=np.add(arr6[0], arr6[1])
arr7

array([[ 5,  7,  9,  5,  7, 15]])

In [81]:
arr7=np.subtract(arr6[0], arr6[1])
arr7

array([[-3, -3, -3, -3, -3, -9]])

In [82]:
arr7=np.multiply(arr6[0], arr6[1])
arr7

array([[ 4, 10, 18,  4, 10, 36]])

In [83]:
arr7=np.divide(arr6[0], arr6[1])
arr7

array([[0.25, 0.4 , 0.5 , 0.25, 0.4 , 0.25]])

In [84]:
np.ceil(arr7)

array([[1., 1., 1., 1., 1., 1.]])

In [85]:
np.floor(arr7)

array([[0., 0., 0., 0., 0., 0.]])

In [86]:
np.round(arr7)

array([[0., 0., 0., 0., 0., 0.]])

**Statistics**

In [87]:
np.mean(arr5)

5.777777777777778

In [88]:
np.mean(arr5, axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.        ,  5.66666667,
       10.        ])

In [89]:
np.mean(arr5, axis=1)

array([2.        , 6.        , 9.33333333])

In [90]:
np.median(arr5)

5.0

In [91]:
np.median(arr5, axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.        ,  5.66666667,
       10.        ])

In [92]:
np.median(arr5, axis=1)

array([2.        , 6.        , 9.33333333])

In [94]:
np.min(arr5)

1

In [95]:
np.min(arr5, axis=1)

array([1, 4, 7])

In [96]:
np.max(arr5)

15

In [97]:
np.max(arr5, axis=1)

array([ 3, 12, 15])

In [101]:
arr8=np.array([1,2,3,4,5,6,7,8,9])
arr8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.argmax(arr8)

8

In [103]:
np.argmin(arr8)

0

In [104]:
np.argsort(arr8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [105]:
np.sin(arr8)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [106]:
np.sin(arr8[0])

0.8414709848078965

In [107]:
np.log(arr8)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [108]:
np.log(arr8[1])

0.6931471805599453