In [4]:
#Practicing Numpy
import numpy as np

In [3]:
arr=np.array([[85,90,78], [92,88,95], [76,95,85],[90,85,92],[88,76,89]])
arr

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [12]:
#Ques1. calculate the mean score of each subject(accross all students)
for i in range(0,5): #if we don't know the range, it should be dynamically dependent on the array's start and end point itself
    print(np.mean(arr[i]))


84.33333333333333
91.66666666666667
85.33333333333333
89.0
84.33333333333333


In [13]:
#Ques2. Find the median score of each student(accross all subjects)
for i in range(0,5):
    print(np.median(arr[i]))

85.0
92.0
85.0
90.0
88.0


In [25]:
#Ques3. extract the scores of the student with highest total score(sum of all subjects)
L=[]
for i in range(0,5):
    score=np.sum(arr[i])
    L.append(score)
print(L)
np.max(L)

[253, 275, 256, 267, 253]


275

In [32]:
#Ques4. Find the min and max scores in each subject
print(np.max(arr, axis=0))
print(np.min(arr, axis=0))

[92 95 95]
[76 76 78]


In [33]:
#Ques5. Reshape the array to have shape(3,5) {current shape is (5,3)}
np.reshape(arr, (3,5))

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [35]:
#Ques6. Sort the scores of each subject in ascending order
print(arr)
np.sort(arr, axis=0)

[[85 90 78]
 [92 88 95]
 [76 95 85]
 [90 85 92]
 [88 76 89]]


array([[76, 76, 78],
       [85, 85, 85],
       [88, 88, 89],
       [90, 90, 92],
       [92, 95, 95]])

**Errors**
Syntax, compile, run, input/output